markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Marcelo Criscuolo
url: http://mcrisc.github.io
description: this is my site
twitter: mcriscuolo
github: mcrisc
picture_url: http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4735775U4
linkedin_url: http://br.linkedin.com/in/mcrisc
lattes_url: http://lattes.cnpq.br/4976779783299858
researchgate_url: https://www.researchgate.net/profile/Marcelo_Criscuolo
gravatar_url: https://2.gravatar.com/avatar/12e1de891d5e73630ace8e6d8404b9f2
