markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Marcelo Criscuolo
url: http://mcrisc.github.io
description: this is my site
twitter: mcriscuolo
github: mcrisc
picture_url: http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4735775U4
linkedin_url: http://br.linkedin.com/pub/marcelo-criscuolo/4/b70/3a5/
lattes_url: http://lattes.cnpq.br/4976779783299858
researchgate_url: https://www.researchgate.net/profile/Marcelo_Criscuolo

