markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Marcelo Criscuolo
url: http://mcrisc.github.io
description: this is my site
twitter: mcriscuolo
github: mcrisc
linkedin_url: http://br.linkedin.com/pub/marcelo-criscuolo/4/b70/3a5/
gravatar_url: http://gravatar.com/avatar/12e1de891d5e73630ace8e6d8404b9f2
